#!/bin/bash

set -euo pipefail

echo '--- cleaning existing git repo'
rm -rf "${BUILDKITE_BUILD_CHECKOUT_PATH}"

echo '--- initializing a git repo'
git init ${BUILDKITE_BUILD_CHECKOUT_PATH}

echo '--- setting remote to the Target git repo for this job'
cd ${BUILDKITE_BUILD_CHECKOUT_PATH}
git remote add origin ${GIT_REPO_URL}

echo '--- fetching head'
git fetch

echo '--- checking out given ref spec'
git reset --hard ${GIT_REF_SPEC}

