#!/bin/bash

set -euo pipefail

echo '--- Cleaning existing git repo'
rm -rf "${BUILDKITE_BUILD_CHECKOUT_PATH}"

echo '--- Initializing a git repo'
git init ${BUILDKITE_BUILD_CHECKOUT_PATH}

echo '--- Setting remote to the Target git repo for this job'
cd ${BUILDKITE_BUILD_CHECKOUT_PATH}
git remote add origin ${GIT_REPO_URL}

echo '--- Fetching head'
git fetch

echo '--- Checking out given ref spec'
git reset --hard ${GIT_REF_SPEC}

